version: '3.7'

services:

  nginx:
    container_name: medcard_prod_nginx
    build: ./nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ../frontend/app/build:/var/www

  api:
    container_name: medcard_prod_api
    build: ../api
    env_file:
      - .env
    volumes:
      - ../api/app:/srv/www
      - ../api/scripts:/scripts
    command: /scripts/init.sh
    ports:
      - "8080:8080"
    tty: true

  mongo:
    container_name: medcard_prod_mongo
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ../mongo/database:/bitnami

