version: '3.7'

services:

  nginx:
    container_name: medcard_stage_nginx
    build: ./nginx
    env_file:
      - .env
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ../frontend/build:/var/www
      - ./logs:/var/log/nginx
    networks:
      - medcard

  api:
    container_name: medcard_stage_api
    build: ./api
    env_file:
      - .env
    volumes:
      - ./api/scripts:/scripts
      - ../api:/srv/www
    command: /scripts/init.sh
    tty: true
    networks:
      - medcard

  mongo:
    container_name: medcard_stage_mongo
    image: 'bitnami/mongodb:latest'
    volumes:
      - ../mongo/database:/bitnami
    networks:
      - medcard

networks:
  medcard:
    name: medcard