version: '3.7'

services:

  frontend:
    container_name: medcard_dev_frontend
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend/scripts:/scripts
      - ../frontend:/srv/www
    command: /scripts/init.sh
    ports:
      - "5000:5000"
    tty: true

  api:
    container_name: medcard_dev_api
    build: ../api
    env_file:
      - .env
    volumes:
      - ../api/app:/srv/www
      - ../api/scripts:/scripts
    command: /scripts/init.sh
    ports:
      - "8080:8080"
    tty: true

  mongo:
    container_name: medcard_dev_mongo
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ../mongo/database:/bitnami